# Generated by Django 6.0.4 on 2026-04-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellbookmodel',
            old_name='user',
            new_name='sell_by',
        ),
    ]
